const listaInvitados = {
    "F001": { responsable: "Francisco y María", cantidad: 2 },
    "F002": { responsable: "Alex y Rosy", cantidad: 4 },
    "F003": { responsable: "Cecilia Ibarra", cantidad: 5 },
    "F004": { responsable: "Sandy y Jorge", cantidad: 2 },
    "F005": { responsable: "Geli Ibarra", cantidad: 2 },
    "F006": { responsable: "Francisco Ibarra", cantidad: 6 },
    "F007": { responsable: "Rigo Ibarra", cantidad: 4 },
    "F008": { responsable: "Faby Ibarra", cantidad: 5 },
    "F009": { responsable: "Edgar Ibarra", cantidad: 4 },
    "F010": { responsable: "Julio Ibarra", cantidad: 3 },
    "F011": { responsable: "Tío min", cantidad: 6 },
    "F012": { responsable: "Tia lucy", cantidad: 2 },
    "F013": { responsable: "Tío Lalo", cantidad: 6 },
    "F014": { responsable: "Tia lidia", cantidad: 4 },
    "F015": { responsable: "Compa Rafa", cantidad: 4 },
    "F016": { responsable: "Tío Armando", cantidad: 2 },
    "F017": { responsable: "Prima Susy", cantidad: 4 },
    "F018": { responsable: "Paty Martinez", cantidad: 4 },
    "F019": { responsable: "Claudia Martinez", cantidad: 4 },
    "F020": { responsable: "Mary Martinez", cantidad: 11 },
    "F021": { responsable: "Gaby Martinez", cantidad: 4 },
    "F022": { responsable: "Kitty Martinez", cantidad: 2 },
    "F023": { responsable: "Edgar sobrino", cantidad: 3 },
    "F024": { responsable: "Dany Martinez", cantidad: 4 },
    "F025": { responsable: "Rafa Beltrán", cantidad: 2 },
    "F026": { responsable: "Adrian Beltrán", cantidad: 2 },
    "F027": { responsable: "Toño Beltrán", cantidad: 2 },
    "F028": { responsable: "Toño ahijado", cantidad: 2 },
    "F029": { responsable: "Padrino Ricardo", cantidad: 4 },
    "F030": { responsable: "Alma Garrett", cantidad: 4 },
    "F031": { responsable: "Ivonne", cantidad: 5 },
    "F032": { responsable: "Lulu y Rafa", cantidad: 2 },
    "F033": { responsable: "Martin y Lucy", cantidad: 2 },
    "F034": { responsable: "Amadeo y dulce", cantidad: 5 },
    "F035": { responsable: "Mariana", cantidad: 4 },
    "F036": { responsable: "Maguito", cantidad: 3 },
    "F037": { responsable: "Xochitl", cantidad: 2 },
    "F038": { responsable: "Graciela", cantidad: 4 },
    "F039": { responsable: "Mtro Sergio", cantidad: 1 },
    "F040": { responsable: "Mtro Rubén", cantidad: 1 },
    "F041": { responsable: "Mtro Alexis", cantidad: 1 },
    "F042": { responsable: "Mtro Daniel", cantidad: 2 },
    "F043": { responsable: "Omar", cantidad: 3 },
    "F044": { responsable: "Director", cantidad: 2 },
    "F045": { responsable: "Subdirector", cantidad: 2 },
    "F046": { responsable: "Mtro Agustín", cantidad: 3 },
    "F047": { responsable: "Paco y Kary", cantidad: 4 },
    "F048": { responsable: "Don Gerry", cantidad: 5 },
    "F049": { responsable: "Susy", cantidad: 2 },
    "F050": { responsable: "Jose Miguel", cantidad: 1 },
    "F051": { responsable: "Graciela Valenzuela", cantidad: 3 },
    "F052": { responsable: "Mtro Eloy", cantidad: 4 },
    "F053": { responsable: "Elba paletería", cantidad: 3 },
    "F054": { responsable: "Celina", cantidad: 2 },
    "F055": { responsable: "Laura estetica", cantidad: 3 },
    "F056": { responsable: "Minerva", cantidad: 5 },
    "F057": { responsable: "Don Lupe", cantidad: 4 },
    "F058": { responsable: "Semi Toño", cantidad: 2 },
    "F059": { responsable: "Pilar", cantidad: 5 },
    "F060": { responsable: "Tío Fer", cantidad: 2 },
    "F061": { responsable: "Vecino Daniel", cantidad: 3 },
    "F062": { responsable: "Mony amiga", cantidad: 3 },
    "F063": { responsable: "Alfredo insunza", cantidad: 2 },
    "F064": { responsable: "Mtra sarah", cantidad: 2 },
    "F065": { responsable: "Angie valle", cantidad: 4 },
    "F066": { responsable: "Primo chava", cantidad: 10 },    
    "F067": { responsable: "Ximena", cantidad: 2 },
    "F068": { responsable: "Isaac", cantidad: 2 }
};